name: pkg-pr-new Publish

on:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  prerelease:
    name: pkg-pr-new Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8.15.4
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build and publish to pkg.pr.new
        working-directory: packages/next
        run: pnpm build; npx pkg-pr-new publish --no-template
